import "./ProfileSettings.css";
import { useEffect, useState } from "react";
import { supabase } from "../../libs/supabase";
import {
  User, Edit, Lock, Bell, Shield, Moon, LogOut, Users, Flame, Wallet, CheckCircle,
} from "lucide-react";
import PagerLoader from "../PagerLoader/PagerLoader";
import CubeIcon from "../../assets/cubecoin-robot-green.png"

export default function ProfileSettings() {
  const [profile,      setProfile]      = useState(null);
  const [referrals,    setReferrals]    = useState(0);
  const [loading,      setLoading]      = useState(true);

  useEffect(() => { fetchProfile(); }, []);

  const fetchProfile = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data: profileData } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", user.id)
        .single();

      // ── Referral count: profiles where referred_by_code = my referral_code ──
      // Uses profiles.referral_code (generated by trigger at signup) as the
      // single source of truth — NOT subscriptions.tx_ref (payment ref).
      let referralCount = 0;
      if (profileData?.referral_code) {
        const { count } = await supabase
          .from("profiles")
          .select("*", { count: "exact", head: true })
          .eq("referred_by_code", profileData.referral_code);
        referralCount = count || 0;
      }

      setProfile(profileData);
      setReferrals(referralCount);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    window.location.href = "/";
  };

  if (loading) return <PagerLoader />;

  return (
    <div className="profile-page">

      {/* PROFILE HERO */}
      <div className="profile-hero">
        <img
          src={profile?.avatar_url || CubeIcon}
          alt="profile"
          className="profile-avatar"
        />
        <h1>{profile?.full_name || "User"}</h1>
        <p>@{profile?.username || "username"}</p>
        <span className="miner-level">Active Miner</span>
      </div>

      {/* STATS */}
      <div className="profile-stats">
        <div className="profile-stat-card">
          <Wallet size={22} />
          <h2>{Number(profile?.cube_balance || 0).toFixed(2)}</h2>
          <p>CUBE Earned</p>
        </div>
        <div className="profile-stat-card">
          <Users size={22} />
          <h2>{referrals}</h2>
          <p>Referrals</p>
        </div>
        <div className="profile-stat-card">
          <Flame size={22} />
          <h2>{profile?.streak || 0}</h2>
          <p>Day Streak</p>
        </div>
      </div>

      {/* ACCOUNT SETTINGS */}
      <div className="settings-card">
        <h3>Account</h3>
        <button className="setting-item"><Edit size={18} /> Edit Profile</button>
        <button className="setting-item"><User size={18} /> Change Username</button>
        <button className="setting-item"><Lock size={18} /> Change Password</button>
      </div>

      {/* PREFERENCES */}
      <div className="settings-card">
        <h3>Preferences</h3>
        <button className="setting-item"><Bell size={18} /> Notifications</button>
        <button className="setting-item"><Moon size={18} /> Dark Mode</button>
      </div>

      {/* SECURITY */}
      <div className="settings-card">
        <h3>Security</h3>
        <div className="security-item">
          <div><Shield size={18} /><span>Email Verification</span></div>
          {profile?.email && <CheckCircle size={18} className="verified" />}
        </div>
        <div className="security-item">
          <div><Shield size={18} /><span>Two-Factor Authentication</span></div>
          {profile?.email && <CheckCircle size={18} className="verified" />}
        </div>
      </div>

      {/* LOGOUT */}
      <button className="logout-btn" onClick={handleLogout}>
        <LogOut size={18} /> Logout
      </button>

    </div>
  );
}